debug=false
spring.thymeleaf.cache=false
angcv.export.url=https://blooming-chamber-41361.herokuapp.com/api/export/5a8cc9b506805e1a4c65c102
spring.jpa.hibernate.ddl-auto=create
spring.datasource.initialization-mode=always
spring.datasource.data=schema.postgresql.sql
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL92Dialect
#spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.url=jdbc:postgresql://dacxsdiebsxsph:dc14b0c344063c5541383448052e970696fe628eb749b35dfca6aa9a59c7ac36@ec2-75-101-138-26.compute-1.amazonaws.com:5432/d7g0n6pv0m56ud
spring.datasource.username=postgres
spring.datasource.password=postgres