debug=false
spring.thymeleaf.cache=false
angcv.export.url=https://blooming-chamber-41361.herokuapp.com/api/export/5a8cc9b506805e1a4c65c102
spring.jpa.hibernate.ddl-auto=none
spring.datasource.initialization-mode=always
spring.datasource.data=schema.postgresql.sql
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL92Dialect
#spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.url=jdbc:postgresql://molqyjjfgwohoy:263fac7a599c61836788ba0c190044dc510399f0479c12762e8daa7bacc6a659@ec2-23-23-80-20.compute-1.amazonaws.com:5432/d54anp6g9ihth6
spring.datasource.username=postgres
spring.datasource.password=postgres